import Head from 'next/head';
import Image from 'next/image';
import Header from '@components/Header';
import Footer from '@components/Footer';
import Layout from '@components/Layout';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Will Christenson</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>Will Christenson</h1>
      </main>

      <Footer />
    </Layout>
  );
}
