import Head from 'next/head';
import Image from 'next/image';
import Footer from '@components/Footer';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Will Christenson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Mr. Specific</h1>
      </main>

      <Footer />
    </div>
  );
}
